### ISSUE TITLE
How to launch the game engine?

### ISSUE THREAD

**Issue by SUKHOIsBluePrint** [GaijinEntertainment/DagorEngine#13]

**Comment by NicSavichev** [comment]
You cannot launch engine, you can build and launch DagorEngine tools (shader compiler, vromfsPacker, dabuild, AssetViewer, DaEditorX, etc.) and build and run "games" (samples projects) - skiesSample and testGI.

**Comment by NicSavichev** [comment]
You can download prebuilt tools / samples binaries [here](https://github.com/GaijinEntertainment/DagorEngine/releases/tag/dagor_2023_10_31)
But these prebuilt binaries don't contain shaders built for tools so in order to run AssetViewer or DaEditorX in samples you have to compile them with:
DagorEngine.git/samples/skiesSample/prog/shaders/compile_shaders_tools.bat
or
DagorEngine.git/samples/testGI/prog/shaders/compile_shaders_tools.bat

built tools shaders are placed here:
DagorEngine.git/samples/skiesSample/tools/common/compiledShaders
DagorEngine.git/samples/testGI/tools/common/compiledShaders
