### ISSUE TITLE
[Question] Node visibility

### ISSUE THREAD

**Issue by vmintf** [GaijinEntertainment/DagorEngine#45]
After modeling in the blender, I look at it in the asset viewer, and I raise a question about Node Visibility.

I wonder how to add multiple nodes to Node visibility,
I don't think there's much information about this, so I'm asking what I should do with the blender and what code I should put in the blk file.

**Comment by NicSavichev** [comment]
I don't fully understand your question, but may be you talk about several initial nodes in model (in Blender) that are not shown in AssetViewer?
This can be caused by the fact dabuild can collapse meshes into one node (for faster rendering).
In case if you need to avoid collapsing (e.g. to animate nodes of model in runtime) you should add `animated_node:b=yes` to object properties of node (it is named so in 3ds Max and I don't know how it is named in Blender).
Alternatively you can specify `all_animated_nodes:b=yes` in asset properties of model (usually done via virtual asset rule in .folder.blk)

**Comment by vmintf** [comment]
I'll try the code first and answer you.

**Comment by vmintf** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/84371372/a2e53a59-f450-4e5b-97d5-67b11f6c0600)
I made a mistake when I was doing something, so I solved it with the code except for the error.

**Comment by vmintf** [comment]
Oh by the way, I don't know if you're going to get a question about War Thunder, but I have a document about custom models (aircraft, tank, armament), but I'm having some difficulty doing it, so I'm just wondering if it'll be renewed later. And I'm also wondering if the document about custom model armament will be added to War Thunder Wiki later.

**Comment by vmintf** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/84371372/7a79e52c-5268-40e3-845b-caf7229c52ba)

I have another question.
After adding animated_node:b=yes, the model is not properly visible in the asset viewer.

Is there a solution to this?

**Comment by NicSavichev** [comment]
1. you somehow added animated_node:b=yes to material, not geom node
2.  your tex0 reference is invalid - is shader expected to render properly without texture?
3. model is not shown at all in AssetViewer, right?
4. need to look at AssetViewer's console (or better log file) for possible reports of encountered problems

**Comment by vmintf** [comment]
If it's geom node, do you mean custom properties based on blender?

**Comment by Ninkorr** [comment]
> If it's geom node, do you mean custom properties based on blender? Or where can I add code to the geom node?
When you have active object, "Object Properties" panel appears in "Dagor" category (in 3D viewport, not in the shader tab). Enter name:type = value and press "+" button to add it.
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/136897560/a7811fe4-d63c-4a08-8df6-ec38e61ae60f)
Object Properties can be edited same way it works for dagormats. Also, you can transfer properties from active object to all selected, if more than one node should have same set of properties.
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/136897560/2c172b61-327c-49e7-8d95-7513a294ab8a)

**Comment by vmintf** [comment]
I will try it tomorrow and reply. Thank you all for always answering my questions.

**Comment by Ninkorr** [comment]
> 1. you somehow added animated_node:b=yes to material, not geom node
Not even to material, just to text editor. To apply changes from text to object properties or dagormat there's dedicated button "Apply from text" right next to the corresponding button "Open as text".
Operator won't be able convert material from the screenshot, since there's no **script:t=""**

Upd: apparently it has no error popup nor message to log, it just silently skips the line, if it can't be processed.

**Comment by vmintf** [comment]
I solved it thx, but I have a question, after exporting the model to the asset viewer, when I went into the War Thunder in game, I saw the fitted model tilted 90 degrees, how do I solve this?

**Comment by NicSavichev** [comment]
Need to change basis vectors, historically we use axis X as forward, axis Z as sideward, axis Y as up for units (tanks, aircraft)

**Comment by vmintf** [comment]
> Need to change basis vectors, historically we use axis X as forward, axis Z as sideward, axis Y as up for units (tanks, aircraft)

I have tried everything according to the War Thunder Wiki, but this time I will try it as you said. I will respond tomorrow.
