### ISSUE TITLE
Older versions? 

### ISSUE THREAD

**Issue by MetalMaxMX** [GaijinEntertainment/DagorEngine#62]
I was checking and I am bit confused but is there a way to access Dagor Engine pre-6.5 versions? Like 6.0, 5.0 and older (https://warthunder.com/en/news/6946-development-dagor-engine-6-0-visual-improvements-effects-and-dlss-en, https://gaijinent.com/news/205) or is that going to be fairly difficult to do?

**Comment by NicSavichev** [comment]
I think it is just impossible. Published version is current (most recent). It can internally contain parts of previous versions (since it is developed evolutionary and reuses most codebase of previous versions) but some parts may be removed (due to being obsolete).
Mentioned FX and DLSS are included in current version of engine.

**Comment by MetalMaxMX** [comment]
Oh, I was just asking for a bit of historical preservation here since, to my knowledge, Dagor has been used all the way back to 2005 or earlier (according to https://www.mobygames.com/group/9903/3d-engine-dagor-engine/), and it had quite a few different features. Like a DirectX 9.0c renderer and all, which is likely deprecated in the current version now. 

It is understandable though if those older versions weren't archived or just outright not available though.
